[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "this_day"
path = "day08/main.rs"

[dependencies]
delay = "0.3.1"
glam = "0.29.2"
num = "0.4.3"

# [profile.dev]
# opt-level = 3
